const { Telegraf, session, Markup } = require('telegraf');
const { generateTravelTips } = require('./ai');
const { generateFlightLink, generateHotelLink, generateTravelServices, generateProtectionServices } = require('./links');

// Initialize bot
const bot = new Telegraf(process.env.BOT_TOKEN);

// Session middleware for storing user data temporarily
bot.use(session({
  defaultSession: () => ({
    planningStep: null,
    destination: null,
    checkIn: null,
    checkOut: null,
    travelerType: null,
    interests: null,
    budget: null
  })
}));

// Start command
bot.start((ctx) => {
  const welcomeMessage = `🌍 Welcome to Voyago Bot!

I'm your AI-powered travel assistant, ready to help you plan amazing trips with personalized recommendations.

✨ What I can do:
• Create custom travel plans based on your preferences
• Find flights, hotels, and experiences
• Provide local insights generated by AI
• Share affiliate links to support the bot (no extra cost to you)

🔒 Privacy: I don't store any personal data - everything stays in our conversation.

Ready to start planning your next adventure?`;

  ctx.reply(welcomeMessage, Markup.inlineKeyboard([
    [Markup.button.callback('🗺️ Plan My Trip', 'start_planning')]
  ]));
});

// Help command
bot.help((ctx) => {
  const helpMessage = `🆘 How Voyago Bot works:

🗺️ /plan - Start planning your trip with guided questions
🏠 /start - Return to main menu

💡 About recommendations:
• Travel tips are generated by AI in real-time
• Links to flights, hotels, and experiences support bot development
• No extra cost for you - same prices as booking directly
• No personal data is stored or shared

🤖 AI-powered insights are generated using free models and may occasionally be unavailable.

Need help? Just type your question!`;

  ctx.reply(helpMessage);
});

// Plan command - start the planning process
bot.command('plan', (ctx) => {
  startPlanningProcess(ctx);
});

// Handle "Plan My Trip" button
bot.action('start_planning', (ctx) => {
  ctx.answerCbQuery();
  startPlanningProcess(ctx);
});

// Start planning process
function startPlanningProcess(ctx) {
  // Reset session
  ctx.session.planningStep = 'destination';
  ctx.session.destination = null;
  ctx.session.checkIn = null;
  ctx.session.checkOut = null;
  ctx.session.travelerType = null;
  ctx.session.interests = null;
  ctx.session.budget = null;

  ctx.reply('🌍 Where would you like to go? \n\nPlease enter your destination city (e.g., "Lisbon", "Paris", "Rome"):');
}

// Handle text messages based on planning step
bot.on('text', async (ctx) => {
  const step = ctx.session.planningStep;
  const text = ctx.message.text.trim();

  switch (step) {
    case 'destination':
      ctx.session.destination = text;
      ctx.session.planningStep = 'dates';
      ctx.reply('📅 When are you planning to travel?\n\nPlease enter your dates in format: DD/MM/YYYY - DD/MM/YYYY\n(e.g., "15/06/2024 - 22/06/2024")');
      break;

    case 'dates':
      if (parseDates(text, ctx.session)) {
        ctx.session.planningStep = 'traveler_type';
        ctx.reply('👥 What type of traveler are you?', 
          Markup.inlineKeyboard([
            [Markup.button.callback('🧳 Solo', 'traveler_solo')],
            [Markup.button.callback('💑 Couple', 'traveler_couple')],
            [Markup.button.callback('👨‍👩‍👧‍👦 Family', 'traveler_family')],
            [Markup.button.callback('👫 Friends', 'traveler_friends')]
          ])
        );
      } else {
        ctx.reply('❌ Please enter dates in the correct format: DD/MM/YYYY - DD/MM/YYYY\n(e.g., "15/06/2024 - 22/06/2024")');
      }
      break;

    case 'budget':
      ctx.session.budget = text;
      await generateTravelPlan(ctx);
      break;

    default:
      // Handle general questions or commands
      ctx.reply('👋 Hi! Use /plan to start planning your trip or /help for more information.');
  }
});

// Handle traveler type selection
bot.action(/traveler_(.+)/, (ctx) => {
  const travelerType = ctx.match[1];
  ctx.session.travelerType = travelerType.charAt(0).toUpperCase() + travelerType.slice(1);
  ctx.session.planningStep = 'interests';
  
  ctx.answerCbQuery();
  ctx.reply('❤️ What are your top interests? (You can select multiple)\n\n💡 Tip: Click to toggle interests on/off, then click Done when ready.', 
    Markup.inlineKeyboard([
      [Markup.button.callback('🏛️ Culture', 'interest_culture'), Markup.button.callback('🍽️ Food', 'interest_food')],
      [Markup.button.callback('🌿 Nature', 'interest_nature'), Markup.button.callback('🏖️ Beach', 'interest_beach')],
      [Markup.button.callback('🌃 Nightlife', 'interest_nightlife')],
      [Markup.button.callback('✅ Done', 'interests_done')]
    ])
  );
});

// Handle interests selection
bot.action(/interest_(.+)/, (ctx) => {
  const interest = ctx.match[1];
  
  if (interest === 'done') {
    // If no interests selected, set default
    if (!ctx.session.interests || ctx.session.interests.length === 0) {
      ctx.session.interests = ['Culture']; // Default interest
    }
    
    ctx.session.planningStep = 'budget';
    ctx.answerCbQuery();
    ctx.reply('💶 What\'s your total budget for this trip?\n\nPlease enter your budget (e.g., "€800", "$1200", "£600"):');
    return;
  }
  
  // Add interest to session
  if (!ctx.session.interests) {
    ctx.session.interests = [];
  }
  
  const interestName = interest.charAt(0).toUpperCase() + interest.slice(1);
  if (!ctx.session.interests.includes(interestName)) {
    ctx.session.interests.push(interestName);
    ctx.answerCbQuery(`${interestName} added!`);
  } else {
    // Remove interest if already selected (toggle functionality)
    ctx.session.interests = ctx.session.interests.filter(i => i !== interestName);
    ctx.answerCbQuery(`${interestName} removed!`);
  }
});

// Parse dates from user input
function parseDates(dateText, session) {
  const dateRegex = /(\d{1,2}\/\d{1,2}\/\d{4})\s*-\s*(\d{1,2}\/\d{1,2}\/\d{4})/;
  const match = dateText.match(dateRegex);
  
  if (match) {
    const [, checkInStr, checkOutStr] = match;
    
    try {
      // Convert DD/MM/YYYY to YYYY-MM-DD
      const checkInParts = checkInStr.split('/');
      const checkOutParts = checkOutStr.split('/');
      
      session.checkIn = `${checkInParts[2]}-${checkInParts[1].padStart(2, '0')}-${checkInParts[0].padStart(2, '0')}`;
      session.checkOut = `${checkOutParts[2]}-${checkOutParts[1].padStart(2, '0')}-${checkOutParts[0].padStart(2, '0')}`;
      
      return true;
    } catch (error) {
      return false;
    }
  }
  
  return false;
}

// Generate complete travel plan
async function generateTravelPlan(ctx) {
  const { destination, checkIn, checkOut, travelerType, interests, budget } = ctx.session;
  
  // Show loading message
  const loadingMsg = await ctx.reply('✨ Creating your personalized travel plan...');
  
  try {
    // Generate AI insights
    const interestsStr = interests.join(', ');
    let aiInsights;
    
    try {
      aiInsights = await generateTravelTips(destination, travelerType, interestsStr);
    } catch (error) {
      aiInsights = 'Local insights loading... Meanwhile, here are top-rated experiences for your destination!';
    }
    
    // Generate affiliate links
    const flightLink = generateFlightLink(destination, checkIn, checkOut);
    const hotelLink = generateHotelLink(destination, checkIn, checkOut);
    const travelServices = generateTravelServices(destination, interestsStr);
    const protectionServices = generateProtectionServices();
    
    // Delete loading message
    await ctx.deleteMessage(loadingMsg.message_id);
    
    // Send travel plan
    const planMessage = `🗺️ Your Custom Travel Plan for ${destination}

✈️ **Flights**
Find the best flight deals for your dates:`;
    
    await ctx.reply(planMessage, Markup.inlineKeyboard([
      [Markup.button.url('🔍 View Flights', flightLink)]
    ]));
    
    const hotelMessage = `🏨 **Accommodation**
Discover highly-rated hotels (8+ rating) in ${destination}:`;
    
    await ctx.reply(hotelMessage, Markup.inlineKeyboard([
      [Markup.button.url('🏨 Book Hotel', hotelLink)]
    ]));
    
    const insightsMessage = `✨ **Local Insights**

${aiInsights}

🎯 **Essential Travel Services**
Everything you need for a smooth trip:`;
    
    // Create service buttons (2 per row)
    const serviceButtons = [];
    for (let i = 0; i < travelServices.length; i += 2) {
      const row = [];
      row.push(Markup.button.url(travelServices[i].title, travelServices[i].link));
      if (travelServices[i + 1]) {
        row.push(Markup.button.url(travelServices[i + 1].title, travelServices[i + 1].link));
      }
      serviceButtons.push(row);
    }
    
    await ctx.reply(insightsMessage, Markup.inlineKeyboard(serviceButtons));
    
    // Send protection services
    const protectionMessage = `🛡️ **Travel Protection & Support**
Stay safe and protected during your journey:`;
    
    const protectionButtons = [];
    for (let i = 0; i < protectionServices.length; i += 2) {
      const row = [];
      row.push(Markup.button.url(protectionServices[i].title, protectionServices[i].link));
      if (protectionServices[i + 1]) {
        row.push(Markup.button.url(protectionServices[i + 1].title, protectionServices[i + 1].link));
      }
      protectionButtons.push(row);
    }
    
    await ctx.reply(protectionMessage, Markup.inlineKeyboard(protectionButtons));
    
    // Final message
    const finalMessage = `🎉 Your travel plan is ready!

💡 **Tips:**
• All links support Voyago Bot development (no extra cost to you)
• Book early for better prices and availability
• Check visa requirements for ${destination}

Ready to plan another trip? Use /plan anytime!`;
    
    await ctx.reply(finalMessage, Markup.inlineKeyboard([
      [Markup.button.callback('🗺️ Plan Another Trip', 'start_planning')]
    ]));
    
    // Reset session
    ctx.session.planningStep = null;
    
  } catch (error) {
    console.error('Error generating travel plan:', error);
    await ctx.deleteMessage(loadingMsg.message_id);
    ctx.reply('❌ Sorry, there was an error generating your travel plan. Please try again with /plan');
  }
}

// Error handling
bot.catch((err, ctx) => {
  console.error('Bot error:', err);
  ctx.reply('❌ Something went wrong. Please try again or use /help for assistance.');
});

module.exports = bot;